# Improve colors
set -g default-terminal "screen-256color"

# Change prefix to Ctrl-a (more ergonomic than Ctrl-b)
unbind C-b
set -g prefix C-b
bind C-a send-prefix

# Start window numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Easy config reload
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# Vi mode
setw -g mode-keys vi

# Mouse support
set -g mouse on

# Don't rename windows automatically
set-option -g allow-rename off
set-option -g default-shell /bin/zsh  # or /bin/bash if you use bash
set-option -g default-command /bin/zsh # or /bin/bash if you use bash
# Better split pane shortcuts
bind | split-window -h
bind - split-window -v

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
